import json
import os

from dotenv import load_dotenv
from groq import Groq

from prompts import SYSTEM_PROMPT

load_dotenv()

client = Groq(
    api_key=os.getenv("GROQ_API_KEY")
)
def analyze_text(text: str) -> dict:
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT,
            },
            {
                "role": "user",
                "content": f"Evaluate the following text:\n\n{text}",
            },
        ],
        temperature=0,
        response_format={"type": "json_object"},
    )

    content = response.choices[0].message.content

    return json.loads(content)
def score_to_label(score: float) -> str:
    if score < 0.15:
        return "Definitely Human"
    elif score < 0.35:
        return "Likely Human"
    elif score < 0.65:
        return "Uncertain"
    elif score < 0.90:
        return "Likely AI"
    else:
        return "Definitely AI"


_LABEL_MESSAGES = {
    "Definitely Human": [
        "Our analysis found strong evidence that this content was written by a human.",
        "This content exhibits characteristics strongly associated with human writing.",
        "We found little evidence suggesting this content was AI-generated.",
        "Based on our analysis, this content is almost certainly human-written.",
    ],
    "Likely Human": [
        "This content is likely to have been written by a human.",
        "Most of the evidence suggests human authorship.",
        "The writing appears predominantly human, although some AI-like characteristics were detected.",
        "Our analysis leans toward this content being human-written.",
    ],
    "Uncertain": [
        "Our analysis found mixed signals and could not confidently determine the origin of this content.",
        "This content contains characteristics of both human and AI writing.",
        "The available evidence is inconclusive.",
        "We cannot confidently determine whether this content was written by a person or generated by AI.",
    ],
    "Likely AI": [
        "This content is likely to have been generated by AI.",
        "Most of the evidence suggests AI-generated writing.",
        "The writing exhibits several characteristics commonly associated with AI-generated text.",
        "Our analysis leans toward this content being AI-generated.",
    ],
    "Definitely AI": [
        "Our analysis found strong evidence that this content was generated by AI.",
        "This content appears to be AI-generated with high confidence.",
        "The writing exhibits multiple characteristics strongly associated with AI-generated text.",
        "Based on our analysis, this content is almost certainly AI-generated.",
    ],
}


def label_to_message(label: str) -> str:
    import random
    return random.choice(_LABEL_MESSAGES[label])